name: management
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  collection: ^1.19.1
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_multi_formatter: ^2.13.7
  flutter_native_splash: ^2.4.6
  fluttertoast: ^8.2.12
  go_router: ^16.0.0
  google_fonts: ^6.2.1
  http: ^1.4.0
  intl: ^0.20.2
  mask_text_input_formatter: ^2.9.0
  package_info_plus: ^8.3.0
  path: ^1.9.1
  path_provider: ^2.1.5
  provider: ^6.1.5
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.png"

flutter_native_splash:
  color: "#F2F3F5"
  image: assets/images/logo.png
  android_12:
    image: assets/images/logo.png
    icon_background_color: "#F2F3F5"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/jsons/
