name: management
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_multi_formatter: ^2.13.7
  fluttertoast: ^8.2.12
  go_router: ^16.0.0
  google_fonts: ^6.2.1
  mask_text_input_formatter: ^2.9.0
  path: ^1.9.1
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/jsons/
